# Generated by Django 5.1.2 on 2024-10-08 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='pratos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('linkDaImagem', models.CharField(default='', max_length=512, unique=True)),
                ('nome', models.CharField(default='', max_length=200, unique=True)),
                ('resumo', models.CharField(default='', max_length=1000)),
            ],
        ),
    ]
