# Generated by Django 5.1.2 on 2024-10-08 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pratos',
            old_name='resumo',
            new_name='descricao',
        ),
        migrations.AddField(
            model_name='pratos',
            name='preco',
            field=models.PositiveIntegerField(default=0, unique=True),
        ),
    ]
